### PR TITLE
iscsi/rbd: Fixed a crash: when to delete a pool info which is inside …

### PR DESCRIPTION
**Pull request by liupan1111**
…g_rbd_pools, we shouldn't only free this pool info, but also remove this pool from g_rbd_pools.

### CODE REVIEW

**Comment by dverkamp-intel** [comment]
Good catch, we should indeed not free the pool_info if it was not allocated for this specific RBD device.

However, I think it would be simpler to just add a reference count to the pool_info structure and only free it when the count reaches 0.  Can you try out this strategy instead?

**Comment by dverkamp-intel** [comment]
Actually, taking a closer look at this pool_info management code, I think it would be better to just remove the complicated code here and just strdup() a new copy of pool_name for each RBD device.  It is not worth the complexity to save a few bytes of allocation. I'm preparing a patch to do this, which should also indirectly fix the bug this PR is fixing, so please ignore my previous review comment.

**Comment by dverkamp-intel** [comment]
Can you please verify that the issue is resolved with commit 2b2ce62?

**Comment by liupan1111** [comment]
Cool, I agree old pool queue is too complex. We pulled your changes and had a test, and it works well. Thanks for quick feedback, you Could close this PR.

**Comment by dverkamp-intel** [comment]
Thanks for testing - closing this since it is resolved.

**Pull request closed without merging**
