### PR TITLE
Add tracking of I/O stats to bdevs

### PR DESCRIPTION
**Pull request by benlwalker**
Per-channel stat tracking

### CODE REVIEW

**Comment by pvonstamwitz** [comment]
This looks good, but it might be better if we update the counters at command complete (i.e. in spdk_bdev_io_complete) rather than at command submit time. There could be a lot of I/O queued up when the io_stat command is called and the stats would indicate better numbers than the actual performance. It is not that big of a deal if the use case is periodic sampling of stats, then everything would average out.

**Comment by pvonstamwitz** [comment]
Can we assign a reviewer to this?

**Comment by benlwalker** [comment]
I nominate you @pvonstamwitz! I'll submit an updated version to address your comments tomorrow (I'm traveling today).

Are there any additional stats you'd like to track?

**Comment by pvonstamwitz** [comment]
I am honored. We are looking at adding "busy time" and "average latency" for reads and writes in later PRs.

**Comment by pvonstamwitz** [comment]
I see this has been uploaded in GerritHub (change 362622). You can close this.

**Pull request closed without merging**
