### PR TITLE
Abstract and move rte_ functions into spdk functions that act ad pass-through functions in env_dpdk

### PR DESCRIPTION
**Pull request by ranjitnoronha**
Since the SPDK code is littered with references to rte_ functions, this make moving SPDK to another infrastructure provider from DPDK cumbersome. 

Here, I have attempted to encapsulate the rte_ reference with spdk functions/references, and then implement the spdk functions as pass-through functions in env_dpdk. 

This will make implementation of SPDK over another infrastructure provider simpler.

### CODE REVIEW

**Comment by ranjitnoronha** [comment]
Hi John,

Sure, lets work together on this.

Will your upcoming changes complete the separation of dpdk and spdk? Or 
will there be components still left to refactor?

Do you have a ballpark timeline on when these commits will complete?

thanks,

--ranjit

**Comment by ranjitnoronha** [comment]
Hi John,

I took a look at the 3 conflicts in question at #136, #148 and #150. The 
conflicts appear largely cosmetic in nature (function name changes 
and/or macro name differences). I have added my comments to your diff 
wherever appropriate.

I would be happy to update my diff once you get a check-in go ahead on 
some of these items.

Also, you mentioned a weekly sync-up call. I would be happy to join the 
call (assuming its early morning or late night), if needed so that we 
could speed things along.

thanks,

--ranjit

**Comment by johnmeneghini** [comment]
Hi Ranjit.

So one problem I see is, we now have two versions of the lcore abstractions.

For example, here are the changes from your pull request for rte_lcore_id:

  Functions calling this function: rte_lcore_id

    File      Function                  Line
 0 env.c     spdk_lcore_id             256 return rte_lcore_id();
 1 threads.c spdk_env_get_current_core  48 return rte_lcore_id();

I’d like to get rid of spdk_env_get_current_core() and use one.

Also, your changes convert all rte_lcore_id() callers to use spdk_lcore_id().  My original pull request - which I closed - did this.  However, because of conflicts with the changes in threads.c, and a request from Ben and Daniel, I removed that that stuff.  

Here’s what your change looks like.  You’ve converted all of the rte_lcore_id() callers.

Functions calling this function: spdk_lcore_id

  File         Function                          Line
0 conf.c       spdk_nvmf_parse_nvmf_tgt          209 acceptor_lcore = spdk_lcore_id();
1 verify.c     work_fn                           332 t->lcore_id = spdk_lcore_id();
2 verify.c     work_fn                           334 snprintf(buf_pool_name, sizeof(buf_pool_name), "buf_pool_%d",
                                                     spdk_lcore_id());
3 verify.c     work_fn                           335 snprintf(task_pool_name, sizeof(task_pool_name),
                                                     "task_pool_%d", spdk_lcore_id());
4 bdev.c       spdk_bdev_io_put_rbuf             139 tailq = &g_need_rbuf_small[spdk_lcore_id()];
5 bdev.c       spdk_bdev_io_put_rbuf             142 tailq = &g_need_rbuf_large[spdk_lcore_id()];
6 bdev.c       _spdk_bdev_io_get_rbuf            361 tailq = &g_need_rbuf_small[spdk_lcore_id()];

* Lines 1-8 of 22, 15 more - press the space bar to display more *

Here’s what mine looks like.  I’ve converted only some of the rte_lcore_id() callers.

Functions calling this function: spdk_lcore_id

  File      Function                          Line
0 conf.c    spdk_nvmf_parse_nvmf_tgt          209 acceptor_lcore = spdk_lcore_id();
1 bdev.c    spdk_bdev_io_put_rbuf             138 tailq = &g_need_rbuf_small[spdk_lcore_id()];
2 bdev.c    spdk_bdev_io_put_rbuf             141 tailq = &g_need_rbuf_large[spdk_lcore_id()];
3 bdev.c    _spdk_bdev_io_get_rbuf            360 tailq = &g_need_rbuf_small[spdk_lcore_id()];
4 bdev.c    _spdk_bdev_io_get_rbuf            363 tailq = &g_need_rbuf_large[spdk_lcore_id()];
5 bdev.c    spdk_bdev_cleanup_pending_rbuf_io 381 TAILQ_FOREACH_SAFE(bdev_io, &g_need_rbuf_small[spdk_lcore_id()], rbuf_link, tmp) {
6 bdev.c    spdk_bdev_cleanup_pending_rbuf_io 383 TAILQ_REMOVE(&g_need_rbuf_small[spdk_lcore_id()], bdev_io, rbuf_link);
7 bdev.c    spdk_bdev_cleanup_pending_rbuf_io 388 TAILQ_FOREACH_SAFE(bdev_io, &g_need_rbuf_large[spdk_lcore_id()], rbuf_link, tmp) {
8 bdev.c    spdk_bdev_cleanup_pending_rbuf_io 390 TAILQ_REMOVE(&g_need_rbuf_large[spdk_lcore_id()], bdev_io, rbuf_link);
9 app.c     spdk_app_init                     354 g_shutdown_event = spdk_event_allocate(spdk_lcore_id(), __shutdown_event_cb,
a reactor.c spdk_reactors_start               522 assert(spdk_get_master_lcore() == spdk_lcore_id());

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
Hi Ranjit.

I’m opening up this conversation to everyone by cc’ing the spdk mail list.

Yes, the upcoming changes we have will complete the separation of dpdk and spdk.  

They will also abstract all of the posix dependencies (e.g. pthread_create becomes spdk_thread_create).

The question about how many components to refactor needs to be agreed upon.  

At this point the feedback I’ve received from Ben and Daniel has been that they don’t want to convert all components at once.  So I’ve been taking my pull requests apart into smaller pieces.  Here is one of my older pull requests for reference.

https://github.com/spdk/spdk/pull/132/commits <https://github.com/spdk/spdk/pull/132/commits>

This can be compared with my current pull request:

SPDK EAL Abstractions <https://github.com/spdk/spdk/pull/150>

and with yours.

Abstract and move rte_ functions into spdk functions that act ad pass-through functions in env_dpdk <https://github.com/spdk/spdk/pull/142>

In terms of timeline, I’d like to complete these changes ASAP.  If we can’t merge everything we have into master relatively soon (like this week) then I’d like to propose that a separate SPDK "platform_abstraction" branch be created (not a Github fork) so all of the environmental changes can be submitted there.  This will allow contributors to develop these changes away from master more quickly, and the process of merging SHAs from the “platform_abstraction” into master can go more slowly.

As was discussed at the Intel Builders conference last week, we should set up a periodic conference call to others in the community can discuss this and other subjects.   I’ll work with Jim, Ben, and Daniel to set that up.

John Meneghini
john.a.meneghini@gmail.com

**Comment by ranjitnoronha** [comment]
Hi John,

Its not clear why we need two different calls 
spdk_env_get_current_core() and spdk_lcore_id() that return 
rte_lcore_id()? Was this meant to be a temporary thing?

Or was there some other reasoning behind this?

In principal, I agree that we should have only a single call, but would 
like to understand why two different calls may be needed.

thanks,

--ranjit

**Comment by johnmeneghini** [comment]
Yes, this is a problem that I introduced.  I’ll fix this in my next pull request - which should arrive today.

John Meneghini
john.a.meneghini@gmail.com

**Comment by benlwalker** [comment]
Closing this. DPDK is entirely abstracted behind the SPDK env library now.

**Pull request closed without merging**
