### PR TITLE
configure: try harder to find Python interpreter

### PR DESCRIPTION
**Pull request by smithfarm**
Fixes: https://github.com/spdk/spdk/issues/227
Signed-off-by: Nathan Cutler <ncutler@suse.com>

### CODE REVIEW

**Comment by smithfarm** [comment]
Ping @peluse

**Comment by smithfarm** [comment]
Note: not tested yet - trying to figure out how

**Comment by smithfarm** [comment]
@peluse Would you be willing to submit this fix to the gerrithub under your own name? I hereby waive all rights to it!

**Comment by peluse** [comment]
Fantastic!!  Will check it out a bit later today. Thanks!

Sent from my iPhone

On Jan 19, 2018, at 9:46 AM, Nathan Cutler <notifications@github.com<mailto:notifications@github.com>> wrote:


@peluse<https://github.com/peluse> Nevermind - I broke down and signed up. Here is the review request: https://review.gerrithub.io/395529

**Comment by smithfarm** [comment]
Merged: https://github.com/spdk/spdk/commit/93bd60e0de6b161567182d965239735bf467e85c

**Comment by jimharris** [comment]
Thanks Nathan!

On Jan 20, 2018, at 4:51 AM, Nathan Cutler <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #228<https://github.com/spdk/spdk/pull/228>.

**Pull request closed without merging**
