### PR TITLE
env: Reserve spdk_malloc/zmalloc/realloc/free for posix env.

### PR DESCRIPTION
**Pull request by johnmeneghini**
- rename spdk_malloc to spdk_aligned_malloc
  - rename spdk_zmalloc to spdk_aligned_zmalloc
  - rename spdk_realloc to spdk_aligned_realloc
  - rename spdk_free to spdk_aligned_free

  These APIs should be used for abstracting POSIX malloc, etc.
  routines.

### CODE REVIEW

**Comment by dverkamp-intel** [comment]
In addition to Jim's question, if the intent is that the "aligned" functions are equivalent to rte_malloc() whereas the non-aligned ones are equivalent to malloc(), maybe a better distinction would be that the rte_malloc() equivalent version should be used for memory that can be a DMA target (and is registered for spdk_vtophys() translation).

**Comment by ranjitnoronha** [comment]
My take on this is that we should include the word dma somewhere in the name instead of aligned (spdk_dma_zmalloc()?), since rte_malloc() and its derivatives are returning device addressable or pinned memory.

If for some reason, we are using pinned memory in SPDK, when unpinned memory should suffice (ie. non-I/O related allocations or ordinary data structures), we should replace those calls to spdk_malloc() with regular mallocs(), to avoid demands on a relatively scarce resource.

I did see a commit a few weeks ago replacing some instances of spdk_malloc() with malloc(). Did we catch all such occurrences or do we need a re-review?

Apologizes if this is duplicating conversations elsewhere that I may have missed.

**Comment by johnmeneghini** [comment]
There’s no reason for the name here.  We can name these APIs anything you want.  Ranjith has suggested using _dma_ in the name.  I also see a changes that uses _phys.

We just want spdk_malloc, spdk_calloc, etc. to be reserved for the POSIX API abstraction.

We also want a clear API that identifies what is allocated from physical, contiguous, memory - which is optimized for DMA/RDMA, and what is allocated from other memory pools. Basically, different environments manage memory differently.  So we need our memory management APIs to describe those different allocation mechanisms.  

spdk_malloc_phys
spdk_phy_malloc
spdk_dma_malloc
spdk_contig_malloc

What rte_malloc does is provide and API that allows the caller to allocate contiguous, aligned, memory that’s optimized for DMA.   

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
Yes, this is exactly what I am thinking.

Yes, we need to catch any commits that confuse spdk_malloc() with malloc().   Today spdk_malloc() uses rte_malloc().  So I don’t think these calls should be confused.  It will probably work just fine - in the current DPDK environment.  But once you move to a different environment these two can’t be confused.

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
Yes, this is the intent.  We need to abstract rte_malloc() clearly because it provides as different kind of memory.

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
I am reworking this change now.

I want to know what to call these functions.

If spdk_aligned_* doesn’t work, please speak up now or forever hold your peace. 

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
If you get a moment,  please take a look at my proposal for what to do about our POSIX dependencies. I sent it out to the list yesterday. Our decision there will have an impact here.

Either way, I like adding dma to the name if only for clarity. I'd support spdk_dma_alloc regardless of our POSIX strategy.



Sent from my Sprint Samsung Galaxy S7.


-------- Original message --------
From: John Meneghini <john.a.meneghini@gmail.com>
Date: 4/27/17 9:23 PM (GMT-07:00)
To: spdk/spdk <reply@reply.github.com>
Cc: spdk/spdk <spdk@noreply.github.com>, Author <author@noreply.github.com>, ranjitnoronha@gmail.com, "Walker, Benjamin" <benjamin.walker@intel.com>, "Harris, James R" <james.r.harris@intel.com>
Subject: Re: [spdk/spdk] env: Reserve spdk_malloc/zmalloc/realloc/free for posix env. (#148)

I am reworking this change now.

I want to know what to call these functions.

If spdk_aligned_* doesn’t work, please speak up now or forever hold your peace.

John Meneghini
john.a.meneghini@gmail.com<mailto:john.a.meneghini@gmail.com>



On Apr 26, 2017, at 12:37 PM, John Meneghini <john.a.meneghini@gmail.com<mailto:john.a.meneghini@gmail.com>> wrote:

There’s no reason for the name here.  We can name these APIs anything you want.  Ranjith has suggested using _dma_ in the name.  I also see a changes that uses _phys.

We just want spdk_malloc, spdk_calloc, etc. to be reserved for the POSIX API abstraction.

We also want a clear API that identifies what is allocated from physical, contiguous, memory - which is optimized for DMA/RDMA, and what is allocated from other memory pools. Basically, different environments manage memory differently.  So we need our memory management APIs to describe those different allocation mechanisms.

spdk_malloc_phys
spdk_phy_malloc
spdk_dma_malloc
spdk_contig_malloc

What rte_malloc does is provide and API that allows the caller to allocate contiguous, aligned, memory that’s optimized for DMA.

John Meneghini
john.a.meneghini@gmail.com<mailto:john.a.meneghini@gmail.com>



On Apr 25, 2017, at 7:50 PM, Jim Harris <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimharris commented on this pull request.

Hi John,

Can you describe why aligned needs to be added? Do you envision a separate set of these APIs for unaligned allocations?

-Jim

**Comment by dverkamp-intel** [comment]
I would prefer spdk_dma_ over spdk_aligned_ for the rte_malloc() family of wrappers.

**Comment by johnmeneghini** [comment]
OK. You’ve got it.  spdk_dma_alloc it is.

Yes, I saw your proposal and I briefly looked at it.  I’ll try to respond by next Monday.

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
OK.  You’ve got it.

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
This pull request has been replaced by https://github.com/spdk/spdk/pull/152
I'm closing this.

**Pull request closed without merging**
