### PR TITLE
Master Pull request for DPDK and Posix abstraction changes.

### PR DESCRIPTION
**Pull request by johnmeneghini**
I don't expect these changes to to in all at once but I want to make this branch available for all to see.

Taken all together, these changes abstract all DPDK dependencies and all Posix dependencies from the following modules.

################################################
[libspdk_nvmf_tgt_app.a]
 
spdk/app/nvmf_tgt/conf.c
spdk/app/nvmf_tgt/nvmf_tgt.c
 
################################################
[libspdk_bdev.a]
 
spdk/lib/bdev/bdev.c
 
################################################
[libspdk_conf.a]
 
spdk/lib/conf/conf.c
 
################################################
[libspdk_copy.a]
 
spdk/lib/copy/copy_engine.c
 
################################################
[libspdk_event.a]
 
spdk/lib/event/app.c
spdk/lib/event/app_config.c
spdk/lib/event/reactor.c
spdk/lib/event/subsystem.c
 
################################################
[libspdk_json.a]
 
spdk/lib/json/json_parse.c
spdk/lib/json/json_util.c
spdk/lib/json/json_write.c
 
################################################
[libspdk_log.a]
 
spdk/lib/log/log.c
 
################################################
[libspdk_nvme.a]
 
spdk/lib/nvme/nvme.c
spdk/lib/nvme/nvme_ctrlr.c
spdk/lib/nvme/nvme_ctrlr_cmd.c
spdk/lib/nvme/nvme_ns.c
spdk/lib/nvme/nvme_ns_cmd.c
spdk/lib/nvme/nvme_pcie.c
spdk/lib/nvme/nvme_qpair.c
spdk/lib/nvme/nvme_quirks.c
spdk/lib/nvme/nvme_rdma.c
spdk/lib/nvme/nvme_transport.c
spdk/lib/nvme/nvme_uevent.c
 
################################################
[libspdk_nvmf.a]
 
spdk/lib/nvmf/direct.c
spdk/lib/nvmf/discovery.c
spdk/lib/nvmf/nvmf.c
spdk/lib/nvmf/rdma.c
spdk/lib/nvmf/request.c
spdk/lib/nvmf/session.c
spdk/lib/nvmf/subsystem.c
spdk/lib/nvmf/transport.c
spdk/lib/nvmf/virtual.c
 
################################################
[libspdk_trace.a]
 
spdk/lib/trace/trace.c
 
################################################
[libspdk_util.a]
 
spdk/lib/util/bit_array.c
spdk/lib/util/fd.c
spdk/lib/util/io_channel.c
spdk/lib/util/string.c

### CODE REVIEW

**Comment by benlwalker** [comment]
I have so far picked off the following:

e2ecccb as pull request #153  
32f27bb as pull request #154 
59072b9 as pull request #155 

Note that I made significant modifications to each of these commits as I picked them off. Please review on the relevant PRs.

I also recommend we drop the following commits entirely:
fbed823, 1bce206, edf25e7 - These are all adding casts but we're intentionally using the GNU C extension to treat void pointers as uint8_t pointers regarding pointer math. If you are unable to change your compiler settings to allow for this, let me know and we'll address it some other way.

6ab852f - As far as we can see, this is a false positive from your linter and not an actual problem.

That accounts for 7 out of 31 of the commits so far. I'll continue to cherry pick and update here.

**Comment by benlwalker** [comment]
I picked out 7a33ab9 (Use SPDK_ERRLOG in lieu of printf) and merged it as commit 2d2fde0

**Comment by benlwalker** [comment]
Also commits 535ce7b, a9f76c9, e5fc0bf, 50ba8e4, 773a739, 849fa93, b838679 are probably taken care of after merging b961d9c. I think you'll have to work through writing your replacement for stdinc.h to know for sure.

**Comment by johnmeneghini** [comment]
OK. Thanks for the progress Ben.

Ed and I will take a look at this as soon as everything shows up in master.

I’ll have to take in inventory of what’s left in the Master pull request.

John Meneghini
john.a.meneghini@gmail.com

**Comment by johnmeneghini** [comment]
Ben,

Here’s the list of what I think has been done so far.  What hasn’t been crossed out still needs to be done.

Do you agree?

/John

* 7eae456c (HEAD -> spdk_eal10, origin/spdk_eal10) trace: Configure env_dpdk to use default log and trace implementation
* 6ab852f9 nvmf: Fix uninitialized variable in subsystem.c
* edf25e71 nvme: Fix clang compile issues in nvme library
* 773a739c event: Convert getpid call to spdk_getpid
* 50ba8e42 rdma: Use spdk thread abstractions
* 6b1342ea nvmf: Create poller registration function
* 2fd3462e system: Move nvmf_tgt conf read functions to separate file
* 73a1318c system: Move conf file read functionality to separate implementation file
* 849fa93d system: Replace perror with SPDK_ERRLOG
* 2bc20fa4 trace: Add env abstractions for trace functionality
* e8ff94c6 system: Integrate env thread changes
* 1bce2064 nvmf: Fix clang pointer sign warnings
* e6b6e79d system: Abstract config file handling
* b838679f system: small pthread abstraction changes in io-channel
* fbed8236 json: Fix void pointer arithmetic issue in json code
* 7fd5b821 env: Replace usage of RTE_MAX_LCORE with SPDK_MAX_LCORE
* 4f3c2523 env: Abstraction for lcore state
* e5fc0bfe system: Remove userspace header file dependencies
* a9f76c91 system: pthread abstraction layer
* 535ce7b5 system: Abstraction layer for standard library functions
* 7a33ab91 log: Use SPDK_ERRLOG in lieu of fprintf(stderr
* 00d04516 system: Replace __thread usgae in io_channel.c
* 415639f3 trace: Implement trace library abstraction
* 3a512245 log: Create abstract log implementation interface
* a70d4403 env: add conditional compile to remove rlimit code
* 59072b95 env: add spdk_memcpy to replace rte_memcpy
* 32f27bb8 env: spdk_mempool improvements
* 74c16e25 env: add additional spdk_lcore abstractions
* e2ecccb3 env: add spdk_ring abstractions to replace rte_ring
* 6855dc56 env: Reserve spdk_malloc/zmalloc/realloc/free for posix env.
* 5e69004f make: Add support for optionally building targets and libraries

John Meneghini
john.a.meneghini@gmail.com

> I have so far picked off the following:
> 
> e2ecccb <https://github.com/spdk/spdk/commit/e2ecccb3423c01ac96a2073ab11c413f2e70f1bc> as pull request #153 <https://github.com/spdk/spdk/pull/153>
> 32f27bb <https://github.com/spdk/spdk/commit/32f27bb80026e73b73abd7e7f0eb83e9af81e68a> as pull request #154 <https://github.com/spdk/spdk/pull/154>
> 59072b9 <https://github.com/spdk/spdk/commit/59072b953699628d0447dcf8734473e26807bc26> as pull request #155 <https://github.com/spdk/spdk/pull/155>
I agree that commits fbed823 <https://github.com/spdk/spdk/commit/fbed8236facac9833bfd2677b7d76df79cc1c360>, 1bce206 <https://github.com/spdk/spdk/commit/1bce2064db31d44d900f41bab52764dcf65320e8>, edf25e7 <https://github.com/spdk/spdk/commit/edf25e716239ec0051df88207e6f70e474177839> can be dropped.  These were the result of the fact that we are using -Wno-pointer-arith and -Wno-pointer-sign when compiling with clang-3.9.1.   We’ve changed this.  Commit 6ab852f <https://github.com/spdk/spdk/commit/6ab852f9e28d39dc021acbb9a0f0951e6dc933c0> was the result of running lint.  We’ve disabled the process that runs lint on this code so you can drop that SHA as well.

I picked out 7a33ab9 <https://github.com/spdk/spdk/commit/7a33ab91a015b20ae94f03315aac3cafd5cbd193> (Use SPDK_ERRLOG in lieu of printf) and merged it as commit 2d2fde0 <https://github.com/spdk/spdk/commit/2d2fde0d7fd038942625dad26c0d62d8216afb51>

**Comment by jimharris** [comment]
Hi John,

I don’t see anything crossed out in either the e-mail or when viewing this from the Github website directly.

-Jim

**Comment by benlwalker** [comment]
Closing old pull requests to stay organized.

**Pull request closed without merging**
